export const PERMISSIONS = {
  // Administration
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',

  // Accounts
  VIEW_ACCOUNTS: 'VIEW_ACCOUNTS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  EDIT_ACCOUNT: 'EDIT_ACCOUNT',
  DEACTIVATE_ACCOUNT: 'DEACTIVATE_ACCOUNT',

  // Journal
  VIEW_JOURNAL: 'VIEW_JOURNAL',
  CREATE_JOURNAL: 'CREATE_JOURNAL',
  POST_JOURNAL: 'POST_JOURNAL',
  REVERSE_JOURNAL: 'REVERSE_JOURNAL',
  DELETE_JOURNAL: 'DELETE_JOURNAL',

  // Party
  VIEW_PARTY: 'VIEW_PARTY',
  CREATE_PARTY: 'CREATE_PARTY',
  EDIT_PARTY: 'EDIT_PARTY',
  DEACTIVATE_PARTY: 'DEACTIVATE_PARTY',

  // Invoice
  VIEW_INVOICE: 'VIEW_INVOICE',
  CREATE_INVOICE: 'CREATE_INVOICE',
  EDIT_INVOICE: 'EDIT_INVOICE',
  POST_INVOICE: 'POST_INVOICE',
  CANCEL_INVOICE: 'CANCEL_INVOICE',

  // Vendor Bill
  VIEW_VENDOR_BILL: 'VIEW_VENDOR_BILL',
  CREATE_VENDOR_BILL: 'CREATE_VENDOR_BILL',
  EDIT_VENDOR_BILL: 'EDIT_VENDOR_BILL',
  APPROVE_VENDOR_BILL: 'APPROVE_VENDOR_BILL',
  POST_VENDOR_BILL: 'POST_VENDOR_BILL',
  CANCEL_VENDOR_BILL: 'CANCEL_VENDOR_BILL',

  // Payment
  VIEW_PAYMENT: 'VIEW_PAYMENT',
  CREATE_PAYMENT: 'CREATE_PAYMENT',
  POST_PAYMENT: 'POST_PAYMENT',
  CANCEL_PAYMENT: 'CANCEL_PAYMENT',

  // Banking
  VIEW_BANKING: 'VIEW_BANKING',
  CREATE_BANKING: 'CREATE_BANKING',
  EDIT_BANKING: 'EDIT_BANKING',

  // Reports
  VIEW_LEDGER: 'VIEW_LEDGER',
  VIEW_TRIAL_BALANCE: 'VIEW_TRIAL_BALANCE',
  VIEW_REPORT: 'VIEW_REPORT',

  // Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

  // Fiscal Year
  VIEW_FISCAL_YEAR: 'VIEW_FISCAL_YEAR',
  CREATE_FISCAL_YEAR: 'CREATE_FISCAL_YEAR',
  EDIT_FISCAL_YEAR: 'EDIT_FISCAL_YEAR',
  ACTIVATE_FISCAL_YEAR: 'ACTIVATE_FISCAL_YEAR',
  CLOSE_FISCAL_YEAR: 'CLOSE_FISCAL_YEAR',
  DELETE_FISCAL_YEAR: 'DELETE_FISCAL_YEAR',

  // Accounting Period
  VIEW_ACCOUNTING_PERIOD: 'VIEW_ACCOUNTING_PERIOD',
  CREATE_ACCOUNTING_PERIOD: 'CREATE_ACCOUNTING_PERIOD',
  EDIT_ACCOUNTING_PERIOD: 'EDIT_ACCOUNTING_PERIOD',
  OPEN_ACCOUNTING_PERIOD: 'OPEN_ACCOUNTING_PERIOD',
  CLOSE_ACCOUNTING_PERIOD: 'CLOSE_ACCOUNTING_PERIOD',
  DELETE_ACCOUNTING_PERIOD: 'DELETE_ACCOUNTING_PERIOD',

  // Credit Note
  VIEW_CREDIT_NOTE: 'VIEW_CREDIT_NOTE',
  CREATE_CREDIT_NOTE: 'CREATE_CREDIT_NOTE',
  EDIT_CREDIT_NOTE: 'EDIT_CREDIT_NOTE',
  APPROVE_CREDIT_NOTE: 'APPROVE_CREDIT_NOTE',
  POST_CREDIT_NOTE: 'POST_CREDIT_NOTE',
  CANCEL_CREDIT_NOTE: 'CANCEL_CREDIT_NOTE',
  DELETE_CREDIT_NOTE: 'DELETE_CREDIT_NOTE',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];