spring.application.name=backend


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/nexaerp
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


server.port=8085




# JWT Configuration
# Required env var: JWT_SECRET (min 256-bit / 32-char string)
app.jwt.secret=${JWT_SECRET:nexaerp-jwt-secret-key-2025-very-long-and-secure-string-minimum-256-bit}
app.jwt.access-token-expiration=900000
#app.jwt.access-token-expiration=60000
app.jwt.refresh-token-expiration=604800000

# Security Configuration
app.security.max-failed-attempts=5
app.security.lock-duration-minutes=30


# Gmail SMTP
# Required env vars: MAIL_USERNAME, MAIL_PASSWORD (use a Gmail App Password)


#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME:your_email@gmail.com}
#spring.mail.password=${MAIL_PASSWORD:your_app_password}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sabbirhasan.private@gmail.com
spring.mail.password=vhcr pjgh mnbj fpor
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# App URL (Frontend)
app.frontend.url=http://localhost:4200


# Default Super Admin
# Required env var: DEFAULT_ADMIN_EMAIL, DEFAULT_ADMIN_PASSWORD
app.default-admin.email=${DEFAULT_ADMIN_EMAIL:admin@example.com}
app.default-admin.password=${DEFAULT_ADMIN_PASSWORD:admin123}